### ISSUE TITLE
TODO: make better content for setting BigFix settings

### ISSUE THREAD

**Issue by jgstew** [jgstew/bigfix-content#2]
- [x] Set "_BESClient_Resource_PowerSaveEnable" once after 2 days in bigfix: https://github.com/jgstew/jgstew.github.io/blob/master/_bfsettings/_BESClient_Resource_PowerSaveEnable.md
- [x] Set command polling to at least once every 6 hours (if unset or set to a longer interval)
- [x] Set initial client settings if unset: https://bigfix.me/fixlet/details/5024

### Related:

- https://bigfix.me/fixlet/details/87
- https://bigfix.me/fixlet/details/6117
- https://bigfix.me/fixlet/details/5024
- https://github.com/jgstew/bigfix-content/tree/master/fixlet/clientsettings
- https://github.com/jgstew/bigfix-content/blob/master/dashboards/ClientSettingsManager.ojo
- https://github.com/jgstew/jgstew.github.io/tree/master/_bfsettings
- https://gist.github.com/jgstew/51a99ab4b5997efa0318

**Comment by jgstew** [comment]
This is now a policy action to enable command polling: https://github.com/jgstew/bigfix-content/blob/master/fixlet/clientsettings/Set%20__BESClient_Comm_CommandPollEnable_%20to%20_1_%20-%20Universal.bes

**Comment by jgstew** [comment]
This should force the command polling interval to be less than once every 6 hours: https://github.com/jgstew/bigfix-content/blob/master/fixlet/clientsettings/Force%20CommandPollInterval%20to%20be%20less%20than%206%20hours%20-%20Universal%20-%20Policy.bes

**Comment by jgstew** [comment]
run once on machines newer than the last 3 days, conservative long term settings only if not already set to something else: 

https://github.com/jgstew/bigfix-content/blob/master/fixlet/clientsettings/Recommended%20Client%20Settings%20-%20Initial%20Provisioning%20Speed%20up%20-%20Long%20term%20settings.bes

**Comment by jgstew** [comment]
added this one: https://github.com/jgstew/bigfix-content/blob/master/fixlet/clientsettings/Set%20__BESClient_Resource_PowerSaveEnable_%20to%20_1_%20after%202%20days%20-%20Universal.bes
